name: Tag Worlds

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * 3'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Git Config
      run: |
        git config --global user.email "ci@katelyngigante.com"
        git config --global user.name "Github Actions"
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r Archipelago/requirements.txt
    - name: Update Index
      run: |
        python3 scripts/tag_worlds.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - uses: stefanzweifel/git-auto-commit-action@v5
    #   with:
    #     file_pattern: index/*.yaml
    #     branch: tagging
    #     create_branch: true
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        branch: tagging
        title: Tag Worlds
        add-paths: 'index/*.yaml'
        reviewers: silasary
