name: Update Index

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Git Config
      run: |
        git config --global user.email "ci@katelyngigante.com"
        git config --global user.name "Github Actions"
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r Archipelago/requirements.txt
    - name: Update Index
      run: |
        python3 scripts/update_index.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: stefanzweifel/git-auto-commit-action@v5
